### ISSUE TITLE
'type' module required but not listed in dependencies

### ISSUE THREAD

**Issue by mikemaccana** [segmentio/utm-params#10]
Simply running `var utm = require('@segment/utm-params')` gives:

    internal/modules/cjs/loader.js:582
        throw err;
        ^

    Error: Cannot find module 'type'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
        at Function.Module._load (internal/modules/cjs/loader.js:506:25)
        at Module.require (internal/modules/cjs/loader.js:636:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Object.<anonymous> (C:\Users\mikem\OneDrive\Documents\appless\appless\node_modules\component-querystr
    ing\index.js:7:12)
        at Module._compile (internal/modules/cjs/loader.js:688:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
        at Module.load (internal/modules/cjs/loader.js:598:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
        at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by mikemaccana** [comment]
Type is https://github.com/Gozala/type#readme which is 7 years old and has no index.js, which is why it can't be loaded.

**Comment by mikemaccana** [comment]
See fix at https://github.com/Gozala/type/pull/3

**Comment by mikemaccana** [comment]
(that said, it's probably better to depend on something better maintained)
